version: "3.7"
services: 
  ssv:
    image: bloxstaking/ssv-node:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yaml:/config.yaml
      - ./:/data
    ports:
      - 13002:13002
      - 12002:12002/udp
    environment:
      - CONFIG_PATH=./config.yaml
    command: make BUILD_PATH=/go/bin/ssvnode start-node
  rockx:
    build:
      context: ./resources/rockx
      dockerfile: build/docker/node/Dockerfile
    command: ./node
    env_file: .env
    restart: on-failure
    ports: 
      - 2505:2505
    volumes:
      - ./keys:/keys
