version: '3.8'
x-base-ssv-node:
  &default-ssv-node
  platform: linux/amd64
  build:
    context: ./lib/ssv
    dockerfile: Dockerfile
  image: ssv:latest
  command: make BUILD_PATH=/go/bin/ssvnode start-node
  network_mode: host
  restart: on-failure
  volumes:
    - ./config:/config
    - ./data:/data

x-base-dkg-node:
  &default-dkg-node
  platform: linux/amd64
  build:
    context: ./lib/dkg
    dockerfile: Dockerfile
  image: dkg:latest
  command: make BUILD_PATH=/go/bin/ssv-dkg start-operator
  network_mode: host
  restart: on-failure
  volumes:
    - ./config:/config
    - ./data:/data
    - ./keys:/keys

services:
  dkg-node:
    <<: *default-dkg-node
    container_name: dkg-node
    environment:
      CONFIG_PATH: ./config/dkg.node.yaml
    ports:
      - 3030:3030

  dkg-node-1:
    <<: *default-dkg-node
    container_name: dkg-node-1
    environment:
      CONFIG_PATH: ./config/dkg.node.1.yaml
    ports:
      - 3031:3031

  dkg-node-2:
    <<: *default-dkg-node
    container_name: dkg-node-2
    environment:
      CONFIG_PATH: ./config/dkg.node.2.yaml
    ports:
      - 3032:3032

  dkg-node-3:
    <<: *default-dkg-node
    container_name: dkg-node-3
    environment:
      CONFIG_PATH: ./config/dkg.node.3.yaml
    ports:
      - 3033:3033

  dkg-node-4:
    <<: *default-dkg-node
    container_name: dkg-node-4
    environment:
      CONFIG_PATH: ./config/dkg.node.4.yaml
    ports:
      - 3034:3034

  dkg-node-5:
    <<: *default-dkg-node
    container_name: dkg-node-5
    environment:
      CONFIG_PATH: ./config/dkg.node.5.yaml
    ports:
      - 3035:3035

  dkg-node-6:
    <<: *default-dkg-node
    container_name: dkg-node-6
    environment:
      CONFIG_PATH: ./config/dkg.node.6.yaml
    ports:
      - 3036:3036

  dkg-node-7:
    <<: *default-dkg-node
    container_name: dkg-node-7
    environment:
      CONFIG_PATH: ./config/dkg.node.7.yaml
    ports:
      - 3037:3037

  dkg-node-8:
    <<: *default-dkg-node
    container_name: dkg-node-8
    environment:
      CONFIG_PATH: ./config/dkg.node.8.yaml
    ports:
      - 3038:3038

  ssv-node:
    <<: *default-ssv-node
    container_name: ssv-node
    environment:
      CONFIG_PATH: ./config/ssv.node.yaml
    ports:
      - 16000:16000
      - 17000:15000

  ssv-node-1:
    <<: *default-ssv-node
    container_name: ssv-node-1
    environment:
      CONFIG_PATH: ./config/ssv.node.1.yaml
    ports:
      - 16001:16001
      - 17001:15001

  ssv-node-2:
    <<: *default-ssv-node
    container_name: ssv-node-2
    environment:
      CONFIG_PATH: ./config/ssv.node.2.yaml
    ports:
      - 16002:16002
      - 17002:15002

  ssv-node-3:
    <<: *default-ssv-node
    container_name: ssv-node-3
    environment:
      CONFIG_PATH: ./config/ssv.node.3.yaml
    ports:
      - 16003:16003
      - 17003:15003

  ssv-node-4:
    <<: *default-ssv-node
    container_name: ssv-node-4
    environment:
      CONFIG_PATH: ./config/ssv.node.4.yaml
    ports:
      - 16004:16004
      - 17004:15004

  ssv-node-5:
    <<: *default-ssv-node
    container_name: ssv-node-5
    environment:
      CONFIG_PATH: ./config/ssv.node.5.yaml
    ports:
      - 16005:16005
      - 17005:15005

  ssv-node-6:
    <<: *default-ssv-node
    container_name: ssv-node-6
    environment:
      CONFIG_PATH: ./config/ssv.node.6.yaml
    ports:
      - 16006:16006
      - 17006:15006

  ssv-node-7:
    <<: *default-ssv-node
    container_name: ssv-node-7
    environment:
      CONFIG_PATH: ./config/ssv.node.7.yaml
    ports:
      - 16007:16007
      - 17007:15007

  ssv-node-8:
    <<: *default-ssv-node
    container_name: ssv-node-8
    environment:
      CONFIG_PATH: ./config/ssv.node.8.yaml
    ports:
      - 16008:16008
      - 17008:15008

  ssv-exporter:
    <<: *default-ssv-node
    container_name: ssv-exporter
    environment:
      CONFIG_PATH: ./config/ssv.exporter.yaml
    ports:
      - 16000:16000
      - 16009:16009
      - 17009:17009