db:
  Path: ./data/db
eth2:
  Network: prater
  BeaconNodeAddr: http://localhost:5052
eth1:
  ETH1Addr: ws://localhost:8546
OperatorPrivateKey: <your-operator-private-key>
p2p:
  UdpPort: <12001-or-your-operator-udp-port>
  TcpPort: <13001-or-your-operator-tcp-port>
