db:
  Path: ./data/ssv-exporter/db
ssv:
  Network: jato-v2
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s
    FullNode: true
    Exporter: true
eth2:
  BeaconNodeAddr: http://127.0.0.1:5052
eth1:
  ETH1Addr: ws://127.0.0.1:8545
GenerateOperatorPrivateKey: true
WebSocketAPIPort: 16000
p2p:
  Subnets: 0xffffffffffffffffffffffffffffffff
  MaxPeers: 150
  UdpPort: 16009
  TcpPort: 17009
